### ISSUE TITLE
Allow duplicate fragments

### ISSUE THREAD

**Issue by JoviDeCroock** [0no-co/GraphQLSP#106]
Currently if we have duplicated fragment use then we report an error, this could be because a component is used multiple times in different sub-components leading to a fragment being used multiple times. We should give people the option to filter out these warnings.

**Comment by nandorojo** [comment]
We use duplicated fragments & nested duplicates so this would be great.

**Comment by nandorojo** [comment]
Oh like two different fragments with the same name?

Never mind then. I think I just needed to restart my TS server.
