### ISSUE TITLE
GraphQL field descriptions in IntelliSense have broken syntax highlighting

### ISSUE THREAD

**Issue by jaydenseric** [0no-co/GraphQLSP#124]
In VS Code, GraphQL field descriptions in IntelliSense have broken syntax highlighting:

<img width="611" alt="Screenshot 2023-12-05 at 5 00 18 PM" src="https://github.com/0no-co/GraphQLSP/assets/1754873/5fa7a279-0447-41be-abf7-e2c2722b5683">

**Comment by JoviDeCroock** [comment]
Yes, I have seen this quite a few times now, there are very few guides out there for VSCode atm. It does seem to look a lot better in other IDE's 😅 I am not really doing anything to ask for this highlighting.

**Comment by JoviDeCroock** [comment]
Yeah, the tsserver logs should be able to give me a clue. There is a type for jsDoc annotations that I avoided using because of doubts that all IDE's implement it

**Comment by jaydenseric** [comment]
Note that GraphQL tooling generally renders GraphQL descriptions as markdown, and so does TypeScript when rendering JSDoc descriptions.

I haven't tried it out, but I would expect to be able to use backticks for inline code blocks, markdown links etc. in the GraphQL schema field descriptions and see them rendered accordingly in the IntelliSense descriptions, same as JSDoc.
