### ISSUE TITLE
Missing autocomplete for mutation variables

### ISSUE THREAD

**Issue by nandorojo** [0no-co/GraphQLSP#127]
<img width="392" alt="Screenshot 2023-12-06 at 10 59 51 AM" src="https://github.com/0no-co/GraphQLSP/assets/13172299/d5e63232-52fc-4d06-b992-afa07fb8a012">

The suggestions it's giving here are the names of other mutations.

**Comment by JoviDeCroock** [comment]
There might be an off by one error here, i.e. works well on a newline etc

**Comment by nandorojo** [comment]
Yeah kinda works with a new line
