### ISSUE TITLE
Fragments not getting picked up

### ISSUE THREAD

**Issue by nandorojo** [0no-co/GraphQLSP#129]
<img width="829" alt="image" src="https://github.com/0no-co/GraphQLSP/assets/13172299/50d8ed95-b079-499f-b897-41cbb3dc7d73">

1. The fragment sometimes doesn't get picked up. Restarting the TS server fixes it.
2. Once it's fixed, I can't right click a fragment to jump to it (the VSCode extension allows this, it's nice). I can open a separate issue here if you want.

**Comment by nandorojo** [comment]
Interesting, would it be possible to add support for it at the place it was defined with the graphql tag though? Would be super useful to keep this behavior for me

**Comment by JoviDeCroock** [comment]
That would require scanning the whole tree as there is no import present 😅

**Comment by JoviDeCroock** [comment]
Just to call this out explicitly the fragment won't get picked up until your code-generator ran, then we indeed rely on TS to tell us this fragment is present in the `graphql` generated file that is imported to construct these documents.

**Comment by nandorojo** [comment]
> Just to call this out explicitly the fragment won't get picked up until your code-generator ran

I don’t think this is necessary. I don’t care about the codegen’d code since I wouldn’t consider this the “source” from the DX perspective.

The VSCode plugin jumps to the definition of the fragment where you named it with the `graphql` function call yourself. This is the ideal behavior if possible, and it doesn’t rely on the codegen.

Let me know if I’m missing something.

> That would require scanning the whole tree as there is no import present 😅

Yeah…that’s the main hesitation I’d have. I wonder if it could scan lazily when you try to jump to the definition to avoid always scanning the tree. Not sure what the TS APIs look like for that.

**Comment by JoviDeCroock** [comment]
You can't jump to a definition that doesn't exist though 😅 in the client-preset every fragment-spread is a magic string that gets resolved by the code-generator.... This means that we can't actually do anything else than scanning the entire tree especially with regards to nested fragments that becomes a really big footgun.

> I don’t think this is necessary. I don’t care about the codegen’d code since I wouldn’t consider this the “source” from the DX perspective.

Yes, but the source is unknown.... Also as an additional callout, some folks add `__typename` and other properties while code-genning which makes it the actual source of truth though.
