### ISSUE TITLE
Warn about unused fields

### ISSUE THREAD

**Issue by thomasheyenbrock** [0no-co/GraphQLSP#143]
Hi all 👋 I just had a thought about a potential feature that could maybe be built into GraphQLSP: Show a warning for any field in a fragment or query that is unused. I could imagine two different kinds of warnings:

1. On the query level, it would make sense to warn about fields that are never used anywhere in my codebase.
2. On the fragment level, I would love to see which fields of my fragment are not used in the co-located component.

**Why?** A common pattern with GraphQL is to co-locate data requirements in the form of GraphQL fragments with UI components. When I refactor a UI component it's easy to add more fields that I need now, however, it's also easy to forget removing a field that I'm no longer using. I would love to have tooling that yells at me to do so 😄

**Comment by nandorojo** [comment]
Fan of this idea as well...although I'd want the ability to blacklist some fields like `id` which I query simply to satisfy the URQL normalized cache.

**Comment by JoviDeCroock** [comment]
There's a start in here but it's proving to be quite complex 😅 https://github.com/0no-co/GraphQLSP/compare/wip-fields?expand=1
