### ISSUE TITLE
Add go-to-definition for fragments

### ISSUE THREAD

**Issue by nandorojo** [0no-co/GraphQLSP#145]
If you use this [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql), you can jump to definition when clicking a fragment name.

This will open the fragment in the place that you wrote it with the `graphql()` method, not where its codegen is output.

It was previously discussed but I wanted to resurface it here, as it would be super useful.

Here's a video of what I mean:

https://github.com/0no-co/GraphQLSP/assets/13172299/860cb4c4-c595-486f-8f25-53e18fc9f910

That DX is 10/10...

But the extension's features clash with this TS plugin so I can't really use them together. If I do, I end up with duplicate suggestions, etc.

**Comment by JoviDeCroock** [comment]
The difference between these two is that we don't own `tsserver` while they do own `graphql-language-server`, this makes the difference that they can store and explore a lot of state while we can't.

[Example](https://github.com/graphql/graphiql/blob/main/packages/graphql-language-service-server/src/GraphQLLanguageService.ts#L447)

**Comment by ya2s** [comment]
@JoviDeCroock 
Isn't it okay to use the same logic as ts-graphql-plugin?
https://github.com/Quramy/ts-graphql-plugin?tab=readme-ov-file#enabledglobalfragments
