### ISSUE TITLE
Field used but still warned as not used

### ISSUE THREAD

**Issue by deathemperor** [0no-co/GraphQLSP#180]
### Describe the bug

maxHP is used in line 39 but still reported as not used

![image](https://github.com/0no-co/gql.tada/assets/4255482/a40a053f-7a64-419f-a45f-f0ff0ef8afe8)

Only happens on root query data, works fine in Fragment. However, id is not reported as not used even both PokemonList and PokemonItem do not use.

![image](https://github.com/0no-co/gql.tada/assets/4255482/0a1cb2e1-3ec4-4270-adc3-e319e9f8717d)

### gql.tada version

gql.tada 1.0.2

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by deathemperor** [comment]
@JoviDeCroock using LSP version 1.0.0 when creating this issue but still happens in 1.0.3

**Comment by JoviDeCroock** [comment]
That does not happen to me for latest, when you upgrade the LSP you have to restart your TSServer.

I did however discover a different bug where overlapping fields can become a nuisance, fixing that in https://github.com/0no-co/GraphQLSP/pull/182

**Comment by deathemperor** [comment]
can confirm it's fixed in 1.0.5

this is not fixed though:
`However, id is not reported as not used even both PokemonList and PokemonItem do not use.`

**Comment by JoviDeCroock** [comment]
@deathemperor `id` and `__typename` are a reserved field for normalised caches and such

**Comment by deathemperor** [comment]
@JoviDeCroock updated my previous comment. issue should still remains open.

**Comment by JoviDeCroock** [comment]
That link reproduces nothing for me 😅

**Comment by deathemperor** [comment]
my bad. that repo doesn't reproduce. our production repo does. Our take more look at it
