### ISSUE TITLE
Generating the introspection .d.ts/ts file programmatically

### ISSUE THREAD

**Issue by rhermelingcoolblue** [0no-co/GraphQLSP#212]
First, I would like to praise you for this amazing library! About my question: How can I generate the introspection file without access to an editor like in a ci/cd pipeline environment?

**Comment by JoviDeCroock** [comment]
Hey,

Thanks for the kind words, you can probably do it exactly the same way as we do it in the LSP https://github.com/0no-co/GraphQLSP/blob/main/packages/graphqlsp/src/graphql/getSchema.ts

**Comment by kitten** [comment]
What I originally had in mind was to add a CLI to `gql.tada` for this, but there's a lot of overlap with `GraphQLSP` potentially, as, I assume, we'd also want to run all the CI checks that `GraphQLSP` performs in a CLI, so there's no concrete plans for this just yet

**Comment by rhermelingcoolblue** [comment]
Thank you, I will take a look at that function. For now the only CI check we do is executing the tsc command within our repo that references the generated introspection file.

**Comment by backmeupplz** [comment]
@JoviDeCroock can we reopen this? I'm not sure how to call the `getSchema` file and what arguments to pass. What we're trying to do is generating the `graphql-env.d.ts` in GitHub Actions to then do `yarn tsc --skipLibCheck` to check if the code compiles.

Ideally would be great to have something like `npx @0no-co/graphqlsp saveSchema` command :)
