### ISSUE TITLE
Language Server appears not to start up

### ISSUE THREAD

**Issue by mattpocock** [0no-co/GraphQLSP#220]
### Describe the bug

I've followed the installation instructions, but the language server doesn't seem to start up. No .d.ts file is created.

I'm using VSCode.

### Reproduction

https://github.com/mattpocock/gql-tada-testing

### gql.tada version

^1.2.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
I suppose this does add some question around debugging, but I think, the answer here is quite simple: `gql.tada` should have a CLI that allows doing all the operations we tell people out of the box.

I've also been thinking that for some cases a `doctor` or `check` subcommand would be useful that checks several pre-conditions 🤔

**Comment by JoviDeCroock** [comment]
We can't surface it no, I have tried a lot of things but I have only managed to surface it in `tsserver`. We're working on https://github.com/0no-co/gql.tada/pull/58 to be able to surface these differently

**Comment by mattpocock** [comment]
OK, makes sense! I'll close this issue as it feels unrelated to the real problem, which you guys have in hand.

**Comment by deathemperor** [comment]
just want to add that folders won't be automatically created so no .d.ts file either
