### ISSUE TITLE
Trouble generating graphql-env.d.ts if project is opened from a folder one level above project with gql.tada

### ISSUE THREAD

**Issue by skalidindi** [0no-co/GraphQLSP#225]
### Describe the bug

Imagine having a monorepo such as
```
monorepo <--- root folder
     - client <----- react codebase with gql.tada installed
```
 
 If I open the monorepo folder with VSCode, graphql-env.d.ts fails to generate. I have tried adding vscode settings at the root level as well as adding typescript as a dep dependency at the root level but graphql-env.d.ts still does not get generated.

graphql-env.d.ts DOES get generated if I open the subfolder i.e client in this case directly.

I have attached a repo to reproduce this where I just coped the example example-pokemon-api codebase and nested it inside my project to simulate a monorepo.
Folder structure:
```
gql-tada-bug <--- root folder
       example-pokemon-api <---- nested example codebase 
```
and the same behavior as above exists

Note: I have deleted graphql-env.d.ts in the repo to show it will not get generated.

Also when root project is opened, none of the autocomplete or type hint features work.

### Reproduction

https://github.com/skalidindi/gql-tada-bug

### gql.tada version

@0no-co/graphqlsp v1.3.4
gql.tada v1.2.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by skalidindi** [comment]
I don't think it makes sense to have tsconfig in the root folder unless I am mistaken? As a workaround, is there any sort of programming way to call tsserver to generate graphql-env.d.ts?

**Comment by JoviDeCroock** [comment]
I mean, everything is a "it depends" looking at that 😅 you can have a root tsconfig to streamline monorepo configs but that's an architectural thing and not really related to this project. That being said, we are building a CLI to generate the `.d.ts` file atm in `tada`.

**Comment by JoviDeCroock** [comment]
Going to close this for now but note that the `gql.tada` canary already allows you to run `pnpm gql-tada generate` when you are in the folder where your tsconfig is located.
