### ISSUE TITLE
LSP suggestions are duplicated

### ISSUE THREAD

**Issue by TheMightyPenguin** [0no-co/GraphQLSP#24]
When triggering autocomplete, I get multiple for the same option

![image](https://user-images.githubusercontent.com/11748696/232127839-54032002-f70b-4cd5-b951-8490c0e95f68.png)

**Comment by TheMightyPenguin** [comment]
@JoviDeCroock gonna try hacking on this one

**Comment by JoviDeCroock** [comment]
Awesome, feel free to report any learnings, I guess it will be related to the `InlineFragment` here 😅

**Comment by TheMightyPenguin** [comment]
Hmmm so I was unable to reproduce this 🤔 I added another example to the project using unions to test this out, but it never reproduced again, I also tried again on the project I originally got this on and nothing (will try again tomorrow, if not we can close this).

At least I got more familiar with debugging this 😅

**Comment by JoviDeCroock** [comment]
I think I ran into this as well by pressing `CMD + Space` a few times while the TypeScript server or the  plugin itself was still bootstrapping. Not entirely sure though 😅 just reporting here

**Comment by JoviDeCroock** [comment]
Closing this for the time being
