### ISSUE TITLE
Race condition when saving file while code is being generated

### ISSUE THREAD

**Issue by TheMightyPenguin** [0no-co/GraphQLSP#25]
I saved my file but seems like it was being overwritten by the plugin at the same time:

![CleanShot 2023-04-14 at 11 53 42](https://user-images.githubusercontent.com/11748696/232128114-f29fb8fd-dd13-4454-a53e-29155d3278f2.png)

**Comment by JoviDeCroock** [comment]
Yes, this is sadly a constraint we'll have to work with now. We could build an additional check when the GraphQL Code Generator async process is done to see whether the file is in a clean state, like [this](https://github.com/0no-co/GraphQLSP/blob/main/src/index.ts#L176). The TS LSP isn't really intended to write stuff however for us it felt like the best DX but yeah there is more safety required for sure.
