### ISSUE TITLE
Support for Node.js style resolution of tsconfig extends

### ISSUE THREAD

**Issue by lee-borsboom** [0no-co/GraphQLSP#265]
As of 1.4.3 support was added whereby the schema is resolved relative to the tsconfig file that configures the plugin. This change enables us to encapsulate our GraphQLSP config in one tsconfig and reuse it in many places via `extends`, which is great, thanks for this addition.

One minor detail that I think has been overlooked is that the path provided to `extends` is permitted to use Node.js style resolution, [as per the docs](https://www.typescriptlang.org/tsconfig#extends). Our GQL schema lives inside a node package and we'd like to leverage that Node.js style resolution, but when doing so the type definitions fail to generate. I believe that failure is caused by the fact that `getRootDir` uses `path.resolve` to resolve the path to the tsconfig file when it should use `require.resolve`.

Thanks again for all your hard work.

**Comment by JoviDeCroock** [comment]
Hey 👋 

Thanks for the kind words! That's a good point about `node_modules`, something like the following should do the trick I guess

```ts
const getRootDir = (
  info: ts.server.PluginCreateInfo,
  tsconfigPath: string
): string | undefined => {
  const tsconfigContents = info.project.readFile(tsconfigPath);
  const parsed = JSON5.parse<TsConfigJson>(tsconfigContents!);

  if (
    parsed.compilerOptions?.plugins?.find(x => x.name === '@0no-co/graphqlsp')
  ) {
    return path.dirname(tsconfigPath);
  } else if (Array.isArray(parsed.extends)) {
    return parsed.extends.find((p: string) => {
      const resolved = require.resolve(p, { paths: [path.dirname(tsconfigPath)] });
      return getRootDir(info, resolved);
    });
  } else if (parsed.extends) {
    const resolved = require.resolve(parsed.extends, { paths: [path.dirname(tsconfigPath)] });
    return getRootDir(info, resolved);
  }
};
```

I currently can't test this with `node_modules` but I can see whether it works correctly for non node_modules 😅

**Comment by lee-borsboom** [comment]
That implementation of `getRootDir` is exactly what I had in mind :)

My workspace extends a `tsconfig` in `node_modules` so this would work for my case, but I do think it'd be valuable to enable Node.js-style resolution of the `schema` option itself.
