### ISSUE TITLE
Support more than one distinct schema in one repository

### ISSUE THREAD

**Issue by mattddean** [0no-co/GraphQLSP#278]
I have two APIs I'd like to make requests to with gql.tada.

I'd love to see graphqlsp support reading from multiple schema files.

It's totally fine IMO to use a different "template" for each if that helps the LSP differentiate between the two schemas.

Example of what I'd like to put in my tsconfig.json file:

```json
{
    ...
    "plugins": [
      {
        "name": "@0no-co/graphqlsp",
        "schema": "http://localhost:3001/graphql",
        "tadaOutputLocation": "../../packages/api/src/api1/schema.generated.d.ts",
        "template": "gql"
      },
      {
        "name": "@0no-co/graphqlsp",
        "schema": "http://localhost:3002/graphql",
        "tadaOutputLocation": "../../packages/api/src/api2/schema.generated.d.ts",
        "template": "graphql"
      }
    ],
    ...
}

**Comment by JoviDeCroock** [comment]
Dupe https://github.com/0no-co/GraphQLSP/issues/264

**Comment by mattddean** [comment]
@JoviDeCroock I looked at that issue and I believe we're looking for two different things. I want to be able to differentiate between the two entirely separate schemas. I don't want the types from all of the schemas to be concatenated into each other.

Unless I'm misunderstanding, the solution proposed in #264 wouldn't have a way to differentiate between the two schemas when making a query.

**Comment by JoviDeCroock** [comment]
Hmm, in that case I misunderstood in that case we might be missing some information here. Are you seeing both `tadaOutputLocations` being respected as a first case could be that TS does not support duplicate plugins being active. If that works you might be running into our default template tags, i.e. if you use `graphqlSchema1` and `graphqlSchema2` does it work?

**Comment by mattddean** [comment]
Yes, both `tadaOutputLocation`s are respected, but the LSP isn't designed to support this, per @kitten: https://discord.com/channels/1082378892523864074/1210514957863485460/1213265117576433705
