### ISSUE TITLE
Plugin activation failed: TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received an instance of Promise

### ISSUE THREAD

**Issue by stef7** [0no-co/GraphQLSP#281]
## Summary

I just installed graphqlsp and gql.tada barely an hour or two ago, and after doing some digging in TS logs I found this error:

```
Info 26   [22:18:04.315] Loading @0no-co/graphqlsp from /Users/Stefano.Perfili/Sites/(site)/node_modules/typescript/lib/tsserver.js/../../.. (resolved to /Users/Stefano.Perfili/Sites/(site)/node_modules/node_modules)
Info 27   [22:18:04.750] [GraphQLSP] config: {"name":"@0no-co/graphqlsp","schema":"apps/graphql-gateway/src/assets/supergraph.graphql","tadaOutputLocation":"./src/graphql-env.d.ts","tadaDisablePreprocessing":true}
Info 28   [22:18:04.750] [GraphQLSP] Setting up the GraphQL Plugin
Info 29   [22:18:04.751] [GraphQLSP] Got root-directory to resolve schema from: [object Promise]
Info 30   [22:18:04.751] Plugin activation failed: TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received an instance of Promise
```

It looks to be related to this – `resolveTypeScriptRootDir()` – which is returning as a promise rather than an immediate string.

<img width="918" alt="Screenshot 2024-04-04 at 10 43 37 pm" src="https://github.com/0no-co/GraphQLSP/assets/1480673/09f77b52-cd0e-4647-80c1-775ef0ffae5c">

I suppose this PR – https://github.com/0no-co/GraphQLSP/pull/277 – resolves it. But technically as it stands this is broken.

... Though https://github.com/0no-co/GraphQLSP/pull/280 just got merged 4 minutes ago so maybe not? 😅

I'll try updating my versions in a few minutes. But there's probably something to look at around semver, specifying dependency versions correctly, and/or coupling these releases into a single workflow.

Was on @0no-co/graphqlsp ^1.7.1 and gql.tada ^1.4.2. (@gql.tada/internal resolved to version 0.1.2 which appears was also released just a couple hours ago)

**Comment by kitten** [comment]
Hm, I think `@gql.tada/internal` was accidentally bumped to `@gql.tada/internal@0.1.2` rather than ``@gql.tada/internal@0.2.0` when this change was made, accidentally putting an incompatible change in range.

This should be resolved in the latest `@0no-co/graphqlsp` version though, so an upgrade should fix it. Not much we can do about this bump retroactively though, unfortunately

**Comment by stef7** [comment]
Now resolved so can be closed, thanks!
