### ISSUE TITLE
Not working with graphql subscriptions

### ISSUE THREAD

**Issue by clayrisser** [0no-co/GraphQLSP#282]
I was able to set this up and get it to work for queries, but it doesn't work for subscriptions.

![2024-04-04-152401_screenshot](https://github.com/0no-co/GraphQLSP/assets/6234038/ad772ceb-8038-4f0d-90eb-82736fc8c3f2)
![2024-04-04-152414_screenshot](https://github.com/0no-co/GraphQLSP/assets/6234038/88f950f4-4a8c-4d94-b1da-5b48cb4a4534)

**Comment by JoviDeCroock** [comment]
This issue was probably meant for tada 😅 this is the lsp repo

**Comment by clayrisser** [comment]
Ok thanks @JoviDeCroock. Any reasons why it's not working for subscriptions?
