### ISSUE TITLE
CLI hook for tada file generation

### ISSUE THREAD

**Issue by SimonRosenau** [0no-co/GraphQLSP#289]
Hey you all!

I currently have an additional generation script in my repository (mono repo), which automatically generates helper types (for `SCALAR`, `ENUM` and `INPUT_OBJECT`) and possible types for the [apollo in memory cache configuration](https://www.apollographql.com/docs/react/caching/cache-configuration/#possibletypes).

It would be very helpful to have some sort of hook, that would execute some command automatically, after generating the tada introspection file. That way I would not have to do this manually or run an additional nodemon script or something.

My initial idea was something like:
```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "@0no-co/graphqlsp",
        "schema": "./../../services/api/src/schema.gql",
        "tadaOutputLocation": "./src/introspection.ts",
        "hooks": {
          "after-generation": "your-command with args e.g. yarn generate"
        },
      }
    ]
  },
}

```

Is this something you would be open to include in your project? If yes, I would also be happy to file a PR for that!

Thanks for this amazing work 🫶🏼

**Comment by JoviDeCroock** [comment]
I don't think we'll make this part of the LSP as we really want to focus on the development process and having to generate the file was kind of a convenience. I wouldn't add more on that side, we however are working on a CLI so you can do something along the lines of `yarn gql-tada generate-output && yarn generate`.

**Comment by WonderPanda** [comment]
We're really looking forward to being able to generate the output file with a CLI. Right now we're checking it in but as our GraphQL schema changes quite often its causing a lot of weirdness with super large diffs and merge conflicts that developers are running in to.

We'd much rather .gitignore this file and then do a fresh generation in CI to make sure that everything is up to date

**Comment by kitten** [comment]
Just on a side-note, that's been released just before this issue was opened, so this should now be less of an issue, as long as you don't check the file in: https://gql-tada.0no.co/devlog/2024-04-15

**Comment by WonderPanda** [comment]
> Just on a side-note, that's been released just before this issue was opened, so this should now be less of an issue, as long as you don't check the file in: https://gql-tada.0no.co/devlog/2024-04-15

I didn't see the announcement! This is amazing. I just updated our CI pipeline this morning to use the new CLI instead of checking in the graphql-env.d.ts file. Thanks for all the incredible work you've been doing for the GraphQL ecosystem
