### ISSUE TITLE
I like this repo

### ISSUE THREAD

**Issue by TheMikeyRoss** [0no-co/GraphQLSP#296]
thank you guys for making this repo

**Comment by kitten** [comment]
Feels bad to close this 😄 But we do appreciate the praise!
If you run into any questions you can find us on Discord (or GH Discussions, if that's more convenient)

**Comment by danielgwilson** [comment]
> thank you guys for making this repo

+1 🎉 

Seriously 👌🏻 

> Feels bad to close this 😄 But we do appreciate the praise!

This seems like a critical sev 1 issue, should probably re-open and pin 📍

**Comment by JoviDeCroock** [comment]
Y'all honestly made my week, thanks you!
