### ISSUE TITLE
How would I use this in CI?

### ISSUE THREAD

**Issue by taobojlen** [0no-co/GraphQLSP#339]
First of all, thanks for this project -- we're adding this to our codebase and it's going drastically improve our devX!

This plugin has some really useful diagnostics, like warning on unused fields. I'd like to set this up so that if a query/fragment has an unused field, it'll fail a CI job. Is it possible to set this up somehow?

**Comment by JoviDeCroock** [comment]
Hey, that's described [here](https://gql-tada.0no.co/get-started/workflows#_4-ci-checks)

**Comment by taobojlen** [comment]
@JoviDeCroock sorry to come back to this now, but as I've gone deeper into this, I've realized that it's actually the field usage diagnostic from this library ([fieldUsage.ts](https://github.com/0no-co/GraphQLSP/blob/main/packages/graphqlsp/src/fieldUsage.ts)) that I really want to capture in CI! it doesn't look like gql.tada supports that. so maybe this is a feature request to run your unused field detection via CLI?

**Comment by kitten** [comment]
the diagnostics are the exact same across the CLI and the LSP plugin. gql.tada's CLI runs the diagnostics themselves basically
