### ISSUE TITLE
Consider making MISSING_OPERATION_NAME_CODE optional.

### ISSUE THREAD

**Issue by collin** [0no-co/GraphQLSP#346]
I've found issues around this and understand this project considers it best practice to include an operation name.

I am however, several dozen graphql queries in to a project that does not name operations and while other features of the LSP/tada are great (phenomenal actually, thank you!) the warnings are intrusive/something I'd rather not approach at the moment.

Is there any chance that stance could be reconsidered to make named operations optional rather than automatically warn?

**Comment by kitten** [comment]
In what context are you using GraphQLSP? If it's in the context of `gql.tada`, then we could consider lowering it to an `info` level, which should make it less intrusive, i.e. depending on your editor and settings it's basically going to show up as a hint.

However, I believe, if you're using it together with graphql-code-generator, I vaguely remember there was a requirement for it, due to type generation.

**Comment by collin** [comment]
I am using this with `gql.tada`. Not through `graphql-code-generator`

The way I use graphql is via a hasura service. I'm using graphql on my back-end services in order to hook into hasura's permissions system.

The "intrusiveness" is mostly to do with the warnings showing up in the editor:

<img width="505" alt="Screenshot 2024-08-01 at 12 15 20" src="https://github.com/user-attachments/assets/17970986-1662-428e-903e-4ce74df3cf58">

I'd rank mostly as an annoyance.

**Comment by kitten** [comment]
oh, I wasn't aware that we highlight the entire document. That should definitely be adjusted as well. I don't think we want to really mark the entire document in this case 🤔

**Comment by JoviDeCroock** [comment]
That's indeed true, the reason for this were historical. When we initially created GraphQLSP it was with tagged-template literals which when uesd often were just the following

```
gql`your-document`
```

Then the code-generator would run and generate types, which would be imported from a co-located file. It would often be confusing when nothing was generated which is the main reason behind flagging the whole document. Generally it would be better for the call-expression equivalent to do this either on the variable-declaration or drop this warning entirely, I do think from an observability perspective this warning is great.
