### ISSUE TITLE
Persisted document id generation not working with fragments

### ISSUE THREAD

**Issue by onionhammer** [0no-co/GraphQLSP#359]
### Describe the bug

When adding a fragment to a query, the persisted string is not being underscored with yellow squigglies

Without fragment:
![image](https://github.com/user-attachments/assets/fcd06641-6daf-480a-a801-6646fd236255)

With fragment:
![image](https://github.com/user-attachments/assets/e2bd810b-7527-4e40-a966-682c700e7c75)

If i use the hint, it puts "undefined" into the string
![image](https://github.com/user-attachments/assets/c8389d66-b47f-4ebe-9340-aa196274e1a3)

### gql.tada version

1.8.9

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
Mind providing a reproduction or writing a test in this repository. I tried to reproduce your bug but did not succeed

**Comment by onionhammer** [comment]
@JoviDeCroock sure, I also found a workaround - just adding in an empty [] after the graphql fixes it.,

No squiggly:
![image](https://github.com/user-attachments/assets/df7d5917-22f1-4f6c-a540-df172aafd9cb)

Squiggly:
![image](https://github.com/user-attachments/assets/da8d1cc1-d7b3-4cee-89d3-b4e3b60d6aa7)

Repro coming shortly..

**Comment by JoviDeCroock** [comment]
@onionhammer I understand what's going on, give me a moment to fix it

**Comment by onionhammer** [comment]
@JoviDeCroock you're too quick, I just published the repro too lol :D
