### ISSUE TITLE
RFC: Support improved schema discovery UX

### ISSUE THREAD

**Issue by cdaringe** [0no-co/GraphQLSP#365]
# Problem

I have wonderful fields on my schema, but I don't recall _what_ the field names are. Consequently, i start typing "a... no that's not it. let's try 'b'! b... no no that's not it. c? ya! c expands to `card`--wonderful!"

# Discussion

ideas:

- add jump-to support types
- inline in the hover context all child fields

**Comment by JoviDeCroock** [comment]
You can always press `CMD + Space` or `CTRL + Space` to view all fields on the type you're on. Go to definition is a lot harder/more expensive, it's possible but might in most cases where the schema is remote be less feasible.

**Comment by cdaringe** [comment]
Super interesting. Both of those key bindings are already used on my computer (cmd + space === spotlight search, ctrl + space === switch keyboard layout).

ill look for the binding definitions in this repo, see if i can remap them

**Comment by JoviDeCroock** [comment]
I mainly meant that we already do all of that but that it's built-in into your editor but you might ahve changed the keybind 😅

**Comment by cdaringe** [comment]
https://stackoverflow.com/questions/51341555/visual-studio-code-shortcut-to-display-autocomplete-list-before-typing

Thx again
